sonar.projectKey=tienda-tech
sonar.projectName=Tienda Tech
sonar.projectVersion=1.0

sonar.sources=tienda-tech-backend
sonar.tests=tienda-tech-backend
sonar.test.inclusions=**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
